description: ""
icon: ""
license: ""
urls: []
name: text-embedding-ada-002
config_file: |
    parameters:
        model: huggingface://bartowski/granite-embedding-107m-multilingual-GGUF/granite-embedding-107m-multilingual-f16.gguf
    name: text-embedding-ada-002
    embeddings: true
    backend: llama-cpp
    known_usecases:
        - FLAG_EMBEDDINGS
    usage: |-
        You can test this model with curl like this:

        curl http://localhost:8080/embeddings -X POST -H "Content-Type: application/json" -d '{
          "input": "Your text string goes here",
          "model": "text-embedding-ada-002"
        }'
files: []
prompt_templates: []
