description: ""
icon: ""
license: ""
urls: []
name: tts-1
config_file: |
    parameters:
        model: en-us-amy-low.onnx
    name: tts-1
    backend: piper
    known_usecases:
        - FLAG_TTS
    download_files:
        - filename: voice-en-us-amy-low.tar.gz
          uri: https://github.com/rhasspy/piper/releases/download/v0.0.2/voice-en-us-amy-low.tar.gz
    usage: |-
        To test if this model works as expected, you can use the following curl command:

        curl http://localhost:8080/tts -H "Content-Type: application/json" -d '{
          "model":"voice-en-us-amy-low",
          "input": "Hi, this is a test."
        }'
files: []
prompt_templates: []
